version: 3
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "A first hello"
      - run: python test.py
  test:
    docker:
      - image: sonarqube
    steps:
      - checkout
      - run: echo "code coverage"
      - run: sonar-scanner \
            -Dsonar.projectKey=Silliarse_tutest \
            -Dsonar.organization=silliarse-github \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=8c21f04e8a034bd99f5f9abec527dad0668fc495
