version: 2.1
orbs:
  codecov: codecov/codecov@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "A first hello"
      - run: python test.py
  coverage:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "code coverage"
      - run: sudo pip install coverage
      - run: coverage run test.py
      - codecov/upload:
         token: c2b5b02e-7329-4dba-b154-a17f83a1c14f
         file: report.xml

workflows:
    version: 2.1
    build_and_test:
      jobs:
       - build
       - coverage
