version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "A first hello"
      - run: python test.py
  test:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "code coverage"
      - run: sudo pip install pytest-cov
      - run: sudo py.test --cov-report=xml --cov=tutest tests/

workflows:
    version: 2
    build_and_test:
      jobs:
       - build
       - test
