version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
 test:
   docker:
     - image: circleci/python:3.7.0
   steps:
     - checkout
     - run:
        name: Running tests
        command:
           test.py
