version: 3
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "A first hello"
      - run: python test.py
  test:
    docker:
      - image: sonarqube
    steps:
      - checkout
      - run: echo "code coverage"

workflows:
    version: 3
    build_and_test:
      jobs:
       - build
       - test
