version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "A first hello"
      - run: python test.py
  coverage:
    docker:
      - image: sonarqube
    steps:
      - checkout
      - run: echo "code coverage"
      - codecov/upload:
        file: {{ coverage_report_filepath }}

workflows:
    version: 2
    build_and_test:
      jobs:
       - build
       - coverage
